# Generated by Django 4.0.6 on 2023-07-29 12:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import trello1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('start_date', models.DateField(null=True, validators=[trello1.models.present_or_future_date])),
                ('due_date', models.DateField(null=True, validators=[trello1.models.present_or_future_date])),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('Done', 'Done'), ('Doing', 'Doing')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('lable', models.CharField(max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_on_board', to='trello1.board')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField(validators=[trello1.models.validate_mobile_number])),
                ('stack', models.CharField(max_length=20)),
                ('company_size', models.CharField(choices=[('1-50', '1-50'), ('50-100', '50-100'), ('100+', '100+')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', models.BigIntegerField(validators=[trello1.models.validate_mobile_number])),
                ('dob', models.DateField()),
                ('job_profile', models.CharField(choices=[('Frontend developer', 'Frontend developer'), ('Backtend developer', 'FBackend developer'), ('Support Engineer', 'Support Engineer')], max_length=30)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('board', models.ManyToManyField(blank=True, related_name='members', to='trello1.board')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=30)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trello1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_checked', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trello1.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello1.member'),
        ),
        migrations.AddField(
            model_name='board',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='trello1.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('board', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('organization', 'name')},
        ),
    ]
