# Generated by Django 4.0.6 on 2023-07-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trello1.organization'),
        ),
    ]
