# Generated by Django 4.0.6 on 2023-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_profile',
            field=models.CharField(choices=[('Frontend developer', 'Frontend developer'), ('Backtend developer', 'Backend developer'), ('Support Engineer', 'Support Engineer')], max_length=30),
        ),
    ]
