# Generated by Django 4.0.6 on 2023-08-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0002_alter_profile_image_alter_profile_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trello1.card'),
        ),
    ]
