# Generated by Django 4.0.6 on 2023-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0002_alter_location_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
