# Generated by Django 4.0.6 on 2023-08-09 09:07

from django.db import migrations, models
import trello1.models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0003_alter_checklist_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True, validators=[trello1.models.present_or_future_date]),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[trello1.models.present_or_future_date]),
        ),
    ]
