# Generated by Django 4.0.6 on 2023-07-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0003_alter_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='trello1.location'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('board', 'name')},
        ),
    ]
