# Generated by Django 4.0.6 on 2023-07-29 09:26

from django.db import migrations, models
import trello1.models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0004_remove_location_organization_organization_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(null=True, validators=[trello1.models.present_or_future_date]),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(null=True, validators=[trello1.models.present_or_future_date]),
        ),
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.ManyToManyField(null=True, related_name='members', to='trello1.board'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
