# Generated by Django 4.0.6 on 2023-08-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0004_alter_card_due_date_alter_card_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Done', 'Done'), ('Doing', 'Doing')], default='ToDo', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist', to='trello1.card'),
        ),
    ]
