# Generated by Django 4.0.6 on 2023-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0005_alter_card_status_alter_checklist_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('organization_admin', 'organization_admin'), ('organization_user', 'organization_user')], default='organization_user', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_profile',
            field=models.CharField(choices=[('Frontend developer', 'Frontend developer'), ('Backend developer', 'Backend developer'), ('Support Engineer', 'Support Engineer')], max_length=30),
        ),
    ]
