# Generated by Django 4.0.6 on 2023-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello1', '0005_alter_card_due_date_alter_card_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.ManyToManyField(blank=True, related_name='members', to='trello1.board'),
        ),
    ]
